import ContactInterface from './ContactInterface';
import ParentInterface from './ParentInterface';
import SchoolInterface from './SchoolInterface';
import HighSchoolInterface from './HighSchoolInterface';
import PriorCollegeInterface from './PriorCollegeInterface';

export default interface ApplicationInterface {
  id: string | null,
  userId: string | null,
  academicYearStart: string,
  academicYearEnd: string,
  academicYear: string | null,
  isSummerApplication: boolean,
  applicationStatus: string | null,
  lastName: string | null,
  firstName: string | null,
  nickName: string | null,
  fullName: string | null,
  ssn: string | null,
  currentContact: ContactInterface,
  permanentContact: ContactInterface,
  gender: number,
  dob: string,
  placeOfBirth: string | null,
  age: number | null,
  homeAtoll: string | null,
  ebeyeKwajResOrLandOwner: boolean,
  martialStatus: number,
  spouseName: string | null,
  hasChildren: boolean,
  children: string | null,
  emergencyContact: ContactInterface,
  parentMartialStatus: number,
  hasFather: boolean,
  hasMother: boolean,
  hasGuardian: boolean,
  father: ParentInterface,
  mother: ParentInterface,
  guardian: ParentInterface,
  
  currentCollege: SchoolInterface,
  degreeSought: string | null,
  collegeStanding: string | null,
  hasPriorCollege: boolean,
  priorCollege: PriorCollegeInterface,
  fieldOfStudy: string | null,
  dateOfGraduation: string,
  dateFinAidNeeded: string,
  highSchool: HighSchoolInterface,

  savingsDividendsInterests: number,
  employmentIncome: number,
  spouseIncome: number,
  governmentSalary: number,
  compensation: number,
  othersResources: number,
  receivedFinAidBefore: boolean,
  receivedFinAidBeforeDate: string,
  educationExpenseTermType: number,
  expenseTermSemesterSpecific: number,
  tuitionType: number,
  tuition: number,
  supplies: number,
  roomAndBoardMonths: number,
  roomAndBoard: number,
  healthInsurance: number,
  miscellaneous: number,
  transportation: number,
  airfare: number,
  totalExpenses: number,
  financialExpenseTermType: number,
  financialExpenseSemesterSpecific: number,
  pellGrant: number,
  collegeScholarship: number,
  otherScholarship: number,
  parentalSupport: number,
  personalAssets: number,
  othersFinancial: number,
  totalFinancial: number,
  totalFinAssistanceNeeded: number,
  awardAmount: number | null,
  approvalStatus: number,
  viewed: boolean,
}