import ContactInterface from './ContactInterface';
import ParentInterface from './ParentInterface';
import SchoolInterface from './SchoolInterface';
import HighSchoolInterface from './HighSchoolInterface';
import PriorCollegeInterface from './PriorCollegeInterface';

export default interface ApplicationInterface {
  id: string | null,
  academicYearStart: Date | null,
  academicYearEnd: Date | null,
  isSummerApplication: boolean,
  applicationStatus: string | null,
  lastName: string | null,
  firstName: string | null,
  nickName: string | null,
  ssn: string | null,
  currentContact: ContactInterface | null,
  permanentContact: ContactInterface | null,
  gender: string | null,
  dob: string,
  placeOfBirth: string | null,
  age: number | null,
  homeAtoll: string | null,
  ebeyeKwajResOrLandOwner: boolean,
  martialStatus: string | null,
  spouseName: string | null,
  hasChildren: boolean,
  children: string | null,
  emergencyContact: ContactInterface | null,
  parentMartialStatus: string | null,
  hasFather: boolean,
  hasMother: boolean,
  hasGuardian: boolean,
  father: ParentInterface | null,
  mother: ParentInterface | null,
  guardian: ParentInterface | null,
  
  currentCollege: SchoolInterface | null,
  degreeSought: string | null,
  collegeStanding: string | null,
  hasPriorCollege: boolean,
  priorCollege: PriorCollegeInterface | null,
  fieldOfStudy: string | null,
  dateOfGraduation: string,
  dateFinAidNeeded: string,
  highSchool: HighSchoolInterface,

  savingsDividendsInterests: number,
  employmentIncome: number,
  spouseIncome: number,
  governmentSalary: number,
  compensation: number,
  othersResources: number,
  receivedFinAidBefore: boolean,
  receivedFinAidBeforeDate: string,
  educationExpenseTermType: string | null,
  expenseTermSemesterSpecific: string | null,
  tuitionType: string | null,
  tuiton: number,
  supplies: number,
  roomAndBoardMonths: number,
  roomAndBoard: number,
  healthInsurance: number,
  miscellaneous: number,
  transportation: number,
  airfare: number,
  totalExpenses: number,
  financialExpenseTermType: string | null,
  financialExpenseSemesterSpecific: string | null,
  pellGrant: number,
  collegeScholarship: number,
  otherScholarship: number,
  parentalSupport: number,
  personalAssets: number,
  othersFinancial: number,
  totalFinancial: number,
  totalFinAssistanceNeeded: number,
}